[package]
name = 'TestCoins'
version = '0.1.1'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '985f19d40457a5f09f2d741b1feca6bf7ba1f8a6'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
test_coins = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
test_coins_extended = "0xb4d7b2466d211c1f4629e8340bb1a9e75e7f8fb38cc145c54c5c9f9d5017a318"

test_token_admin = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
test_token_extended_admin = "0xb4d7b2466d211c1f4629e8340bb1a9e75e7f8fb38cc145c54c5c9f9d5017a318"
test_account = "0x15"